name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        rust_version:
          - stable
          - "1.74.0" # MSRV
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Add clippy
        run: rustup component add clippy
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cargo
      - name: Install cargo-all-features
        run: cargo install cargo-all-features
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test-all-features -v -- --nocapture
        env:
          RUST_LOG: debug
  cross:
    timeout-minutes: 10
    name: cross
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu
          # - aarch64-linux-android
          # - i686-linux-android
          # - x86_64-linux-android
          #- mips64-unknown-linux-gnuabi64
          #- x86_64-apple-darwin
          #- aarch64-apple-darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: cross test
        run: |
          cargo install cross
          cross test -r --target ${{ matrix.target }}
